version: 2.1

jobs:
  hello-world:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "Hello world! 2"

workflows:
  build:
    jobs:
      - hello-world:
          name: anyb
      - hello-world:
          name: mainjob
          filters:
            branches:
              only:
                - main
